version: '3'

services:
  nginx:
    container_name: nginx
    hostname: nginx
    build:
      context: ./Deploy/Docker/web/nginx
      dockerfile: Dockerfile

  php:
    container_name: php
    hostname: php
    build:
      context: ./Deploy/Docker/web/php
      dockerfile: Dockerfile

  mysql:
    container_name: mysql
    hostname: mysql
    image: mysql:5.7
    command:
      - --explicit_defaults_for_timestamp
      - --character-set-server=utf8
      - --collation-server=utf8_unicode_ci
      - --skip-character-set-client-handshake
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}