version: '3'

services:
  nginx:
    build:
      context: ./Deploy/Docker/web/nginx
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./Code/public/:/code
    depends_on:
      - php
    networks:
      - internal

  php:
    build:
      context: ./Deploy/Docker/web/php
      dockerfile: Dockerfile
    volumes:
      - ./Code/public/:/code
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp
    networks:
      - internal

  mysql:
    deploy:
      replicas: 1
    ports:
      - "0.0.0.0:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp
    networks:
      - internal

networks:
  internal: {}