version: '3'

services:
  nginx:
    image: localhost:5000/nginx
    ports:
      - "0.0.0.0:8080:80"
    volumes:
      - ./Code/public/:/code

  php:
    image: localhost:5000/php
    volumes:
      - ./Code/public/:/code
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp

  mysql:
    deploy:
      replicas: 1
    ports:
      - "0.0.0.0:3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=webapp
      - MYSQL_USER=webapp
      - MYSQL_PASSWORD=webapp
